<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>avatar_button</name>
   <tag></tag>
   <elementGuidId>9bad97e7-5f5b-4beb-9cd4-da82630f6aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user-links&quot;]/li[2]/details/summary/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user-links&quot;]/li[2]/details/summary/span</value>
   </webElementProperties>
</WebElementEntity>
